import type { Metadata } from "next";
import Head from 'next/head';
import { Inter } from "next/font/google";
import './globals.css';
import { CustomProviders } from "@/components/nextauth/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Renewlabour",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CustomProviders>
      <html lang="en">
        <head>
          <link href="https://fonts.googleapis.com/css?family=Kanit&display=optional" rel="stylesheet" />
          <link rel="icon" type="image/x-icon" href="../Logo/logosmall.png"></link>
        </head>
        <body className={inter.className} style={{}}>{children}</body>
      </html>
    </CustomProviders>
  )
}
