import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './globals.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Renewlabour",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css?family=Kanit" rel="stylesheet" />
        <link rel="icon" type="image/x-icon" href="../Logo/logosmall.png"></link>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
